# Using solid_cable in development for consistent behavior with production
development:
  adapter: solid_cable

test:
  adapter: test

production:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
